version: "2"
run:
  timeout: 5m
linters:
  default: all
  disable:
    - depguard
    - gochecknoglobals
    - ireturn
    - nlreturn
    - noinlineerr
    - paralleltest
    - testpackage
    - wrapcheck
    - wsl
    - wsl_v5
  settings: 
    exhaustruct:
      allow-empty: true
    gosec:
      excludes:
        - G104
        - G302
        - G304
        - G703
    mnd:
      ignored-functions:
        - os.MkdirAll
    revive:
      enable-default-rules: true
  exclusions:
    generated: lax
    presets:
      #- comments
      - common-false-positives
      #- legacy
      - std-error-handling
    warn-unused: true
    paths:
      - example/main.go

formatters:
  enable:
    - gofumpt
    - golines
  settings:
    golines:
      max-len: 120
  exclusions:
    generated: lax
issues:
    max-same-issues: 0
    max-issues-per-linter: 0
